version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - pnpm-store:/app/.pnpm-store

volumes:
  node_modules:
  pnpm-store:
