version: '3'

services:
  frontend:
    build: .
    environment:
      LOG_LEVEL: debug
      OTEL_SERVICE_NAME: frontend
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_SAMPLING_RATE: 1
      NEXT_TELEMETRY_DISABLED: 1
    ports:
      - 3000:3000

  jaeger:
    image: jaegertracing/jaeger:2.11.0
    ports:
      - 16686:16686
