services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - pnpm-store:/app/.pnpm-store
      - next:/app/.next

volumes:
  node_modules:
  pnpm-store:
  next:
