name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Format check
        run: pnpm format:check
      - name: Type check
        run: pnpm type-check
      - name: Lint check
        run: pnpm lint
      - name: CSS lint check
        run: pnpm lint:style
      - name: Unit test
        run: pnpm test
      - name: Build check
        run: pnpm build
      - name: Storybok build check
        run: pnpm build-storybook
